--- #YAML:1.0
name:               Sendmail-AccessDB
version:            1.03
abstract:           An interface to Sendmail access.db
author:
    - Derek J. Balling (dredd@megacity.org)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    BerkeleyDB:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
